name: CI - Build and Check Flask App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t best-devops-app .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name myapp best-devops-app

      - name: Wait for the app to be ready
        run: sleep 10

      - name: Check if Flask app is responding
        run: curl -f http://localhost:5000 || exit 1

      - name: Show running containers
        run: docker ps

      - name: Show container logs if test failed
        if: failure()
        run: docker logs myapp
