name: Deploy to Docker

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["CI - Build and Test Flask App"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: maxibona771/best-devops-app:latest
